#!/bin/bash

# default file copies first run
if [ ! -f $HOME/.sparrow/config ]; then
    mkdir -p $HOME/.sparrow
    cp /defaults/.sparrow/config $HOME/.sparrow/config
fi

if [ ! -f $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml ]; then
    mkdir -p $HOME/.config/xfce4/xfconf/xfce-perchannel-xml
    cp /defaults/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml
fi

# open files and directories with thunar (file manager)
xdg-mime default thunar.desktop inode/directory

/opt/sparrow/bin/Sparrow &
